name: ci

on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install project dependencies
      run: npm i
    - name: Build prod
      run: npx ng build --prod --base-href "https://makimenko.github.io/vect/" --output-path ./dist/gh-pages-deploy
    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        name: spa
        path: ./dist/gh-pages-deploy 
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download spa
        uses: actions/download-artifact@v1
        with:
          name: spa
          path: dist
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
